name: IP Scraper

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape-ip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run IP scraper
        run: python ip_scraper.py
      
      - name: Commit and push changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add current_ip.txt ip_scraper.log
            git commit -m "Update IP address"
            git push
          else
            echo "No changes to commit"
          fi    
