name: IP Scraper

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape-ip:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # 授予写入权限
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用默认令牌
          fetch-depth: 0  # 获取完整历史记录
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      
      - name: Run IP scraper
        run: python ip_scraper.py
      
      - name: Commit and push changes
        if: github.event_name == 'workflow_dispatch' || github.event.schedule  # 仅在计划或手动触发时执行
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add ip.txt ip_scraper.log
            git commit -m "Update top IPs"
            git push
          else
            echo "No changes to commit"
          fi
