name: IP 数据采集

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape-ip:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 写入权限（提交文件）
      actions: write   # 删除运行记录的权限

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: 运行 IP 采集脚本
        run: python ip_scraper.py

      - name: 提交并推送更改
        if: github.event_name == 'workflow_dispatch' || github.event.schedule
        run: |
          if [[ $(git status --porcelain) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add 89.txt
            git commit -m "更新 IP 数据"
            git push
          else
            echo "无更改需要提交"
          fi

      - name: 清理旧运行记录（保留最近12条）
        runs-on: ubuntu-latest
        needs: scrape-ip  # 依赖主任务完成后清理
        steps:
          - name: 安装 GitHub CLI 和 jq
            run: |
              # 安装 GitHub CLI
              type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
              curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
              && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
              && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
              && sudo apt update \
              && sudo apt install gh -y

              # 安装 jq
              sudo apt install jq -y

          - name: 认证并清理旧记录
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: |
              gh auth login --with-token <<< "$GITHUB_TOKEN"
              WORKFLOW_NAME="IP 数据采集"
              WORKFLOW_ID=$(gh workflow list --json name,id | jq -r --arg name "$WORKFLOW_NAME" '.[] | select(.name == $name) | .id')
              RUN_IDS=$(gh run list --workflow $WORKFLOW_ID --limit 100 --json databaseId,createdAt \
                        | jq -r 'sort_by(.createdAt) | reverse | .[12:] | .[].databaseId')
              for RUN_ID in $RUN_IDS; do
                  echo "删除旧记录: $RUN_ID"
                  gh run delete $RUN_ID --confirm
              done
